### ISSUE TITLE
Add disclaimer modal

### ISSUE THREAD

**Issue by atomtay** [MAPC/zoning-atlas#16]
Upon entering the site, users should see a modal with a disclaimer about the data (it's constantly evolving, meant as a reference but not definitive source, etc). One example of this is in Massbuilds.

**Comment by theryankelly** [comment]
Slight padding issue on "continue" 

Chrome

![image](https://user-images.githubusercontent.com/2421382/101690218-3a44c900-3a3b-11eb-8f23-a59c774537d3.png)

**Comment by theryankelly** [comment]
Also should it be "Atlas"?
