### ISSUE TITLE
Returning to Reports Formatting Load Issue

### ISSUE THREAD

**Issue by theryankelly** [MAPC/zoning-atlas#19]
When returning to /reports from external link (hpp) the formatting takes a second to kick in

Chrome Version 87.0.4280.88 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/2421382/101509876-39326f80-3947-11eb-9222-ee0e5b15b46c.png)

**Comment by atomtay** [comment]
This seems to have been resolved by adding the SCSS import into `gatsby-browser.js` (which in turn returns the wrapping context component loaded on every page). I'm no longer able to replicate it and so am closing this out for now, but folks should re-open if they notice it again.
