### ISSUE TITLE
Add Social Card Image

### ISSUE THREAD

**Issue by theryankelly** [MAPC/zoning-atlas#34]

**Comment by theryankelly** [comment]
Can this be a gif? Maybe one of the layers gifs? What dimension are needed? 

![image](https://user-images.githubusercontent.com/2421382/102510746-f878db80-4055-11eb-836b-0a622eca30a6.png)

**Comment by theryankelly** [comment]
@elisemaeharmon @Kit-Un thoughts on image to choose? Should we go with just logo file? 

@atomtay I still think the old abstract triangles deserves a spot in the sun

**Comment by Kit-Un** [comment]
How about pg 9 from the prez? https://mapc365.sharepoint.com/:p:/s/DataServicesSP/EXXMRPI-d85MsptzK7LgCnIBNdnuIAYKUmnZnGdUwav3mw?e=rUgmYt OR just the logo file...

**Comment by theryankelly** [comment]
I think the image. I think it would communicate the regional nature of the atlas. Might want to throw text Zoning Atlas with the current text as tag line.

![image](https://user-images.githubusercontent.com/2421382/102513921-d84b1b80-4059-11eb-9c40-f9b23a4df190.png)

**Comment by theryankelly** [comment]
While not the official zoning for 101 towns. Regional zoning abstraction doesn't roll off the tongue in same way

**Comment by theryankelly** [comment]
How about this?

![Zoning Atlas Social](https://user-images.githubusercontent.com/2421382/102517457-0cc0d680-405e-11eb-9d5e-285031c92b5a.PNG)

**Comment by Kit-Un** [comment]
That works!
