### ISSUE TITLE
Add Zoning Report as "Publication" on MetroCommon

### ISSUE THREAD

**Issue by theryankelly** [MAPC/zoning-atlas#39]

**Comment by theryankelly** [comment]
@Kit-Un can you create a publication page on Digital Hub based on the Introduction to Zoning Atlas text and links to report and site included. Will also need to choose a photo to represent publication on Find Out.

Potential Text:

> Originally identified as one of the top ten "Most Wanted Datasets" in MetroFuture: Making a Greater Boston Region, the MAPC Zoning Atlas is a data product nine years in the making. It is the first regional zoning map since 1999, and the first to include information about multifamily housing, residential density, commercial density, and overlay districts.
> 
> [Introduction to the Zoning Atlas](https://zoningatlas.mapc.org/reports/1) is the first research brief to come from this massive undertaking. It outlines the processes and challenges of collecting and synthesizing 101 municipal zoning codes into one unified resource. Zoning codes can be remarkably complex, and discrepancies in their storage, maintenance, accessibility, and interpretation make creating a regional overview both difficult and necessary to achieve.
> 
> The Zoning Atlas will always be a work in progress, and it will rely on municipal collaboration and community input in order to best serve its purpose. As it continues to grow and develop, we hope it will be useful to municipal staff, researchers, and advocates in their work to build a better Greater Boston. Visit the Site at https://zoningatlas.mapc.org/

**Comment by Kit-Un** [comment]
All set!
