### ISSUE TITLE
Re-style basemap selector as toggle

### ISSUE THREAD

**Issue by atomtay** [MAPC/zoning-atlas#5]
Currently, the basemap selector uses the default Leaflet styles. According to the XD, it should be a toggle in the same style as the data view.

This is somewhat complicated by the additional of a third basemap (Mapbox Basic gray); the basemap is no longer boolean based, so an on/off toggle doesn't quite work.

**Comment by theryankelly** [comment]
Now have three basemaps, and will use menu.
